/**
 * notebook.js — .ipynb Notebook 내보내기
 * ResearchMethodAgent v5.0 — Phase 7
 *
 * 체크된 분석 항목을 Jupyter Notebook (.ipynb) 형식으로 조합하여 다운로드.
 * Kaggle / Google Colab에서 바로 실행할 수 있도록 구성.
 */

const REFERENCE_MAP = {
  kaggle: { label: 'Kaggle Code', url: 'https://www.kaggle.com/code' },
  sklearn: { label: 'scikit-learn', url: 'https://scikit-learn.org/stable/' },
  pydsh: { label: 'Python Data Science Handbook', url: 'https://jakevdp.github.io/PythonDataScienceHandbook/' },
};

/* ---- 셀 헬퍼 ---- */

function markdownCell(source) {
  return {
    cell_type: 'markdown',
    metadata: {},
    source: Array.isArray(source) ? source : source.split('\n').map((l, i, a) => i < a.length - 1 ? l + '\n' : l),
  };
}

function codeCell(source) {
  return {
    cell_type: 'code',
    execution_count: null,
    metadata: {},
    outputs: [],
    source: Array.isArray(source) ? source : source.split('\n').map((l, i, a) => i < a.length - 1 ? l + '\n' : l),
  };
}

/* ---- 노트북 조합 ---- */

/**
 * 체크된 분석 항목으로 .ipynb JSON을 생성
 * @param {Object} menu — 3-group menu ({ descriptive, inferential, visualization })
 * @param {Object|null} mockDataCache — { csv, variables, ... }
 * @returns {Object} — .ipynb JSON 객체
 */
function buildNotebook(menu, mockDataCache) {
  const cells = [];
  const groups = ['descriptive', 'inferential', 'visualization'];

  // 타이틀 셀
  cells.push(markdownCell('# 📊 Research Method Agent — Analysis Notebook\n\nThis notebook was auto-generated by **ResearchMethodAgent v5.0**.  \nYou can run it on [Kaggle](https://www.kaggle.com/code) or [Google Colab](https://colab.research.google.com/).'));

  // 참고 자료 셀
  cells.push(markdownCell([
    '## 📚 Reference Resources\n',
    `- [${REFERENCE_MAP.pydsh.label}](${REFERENCE_MAP.pydsh.url})\n`,
    `- [${REFERENCE_MAP.sklearn.label}](${REFERENCE_MAP.sklearn.url})\n`,
    `- [${REFERENCE_MAP.kaggle.label}](${REFERENCE_MAP.kaggle.url})\n`,
  ]));

  // 환경 설정 셀
  cells.push(markdownCell('## ⚙️ Environment Setup'));
  cells.push(codeCell([
    '# 필요한 패키지 설치 (Colab/Kaggle 환경)\n',
    '# !pip install pandas numpy scipy statsmodels scikit-learn matplotlib seaborn pingouin\n',
    '\n',
    'import pandas as pd\n',
    'import numpy as np\n',
    'import matplotlib.pyplot as plt\n',
    'import seaborn as sns\n',
    'import warnings\n',
    'warnings.filterwarnings("ignore")\n',
    'plt.rcParams["figure.figsize"] = (8, 5)\n',
  ]));

  // CSV 데이터 로딩 셀
  cells.push(markdownCell('## 📁 Data Loading'));
  if (mockDataCache && mockDataCache.csv) {
    const csvLines = mockDataCache.csv.split('\n');
    const truncated = csvLines.length > 52 ? csvLines.slice(0, 52).join('\n') + '\n# ... (truncated)' : mockDataCache.csv;
    cells.push(codeCell([
      '# Mock data generated by ResearchMethodAgent\n',
      'from io import StringIO\n',
      '\n',
      'csv_data = """\n',
      truncated + '\n',
      '"""\n',
      '\n',
      'df = pd.read_csv(StringIO(csv_data))\n',
      'print(f"Shape: {df.shape}")\n',
      'df.head()\n',
    ]));
  } else {
    cells.push(codeCell([
      '# CSV 파일 경로를 지정하세요\n',
      'df = pd.read_csv("your_data.csv")\n',
      'print(f"Shape: {df.shape}")\n',
      'df.head()\n',
    ]));
  }

  // 변수 자동감지 셀
  cells.push(markdownCell('## 🔍 Variable Auto-Detection'));
  cells.push(codeCell([
    '# 변수 자동감지 — 실제 데이터에 맞게 수정하세요\n',
    '_num_df = df.select_dtypes(include="number")\n',
    '_skip = ["id", "ID", "entity_id", "Unnamed: 0", "year", "time"]\n',
    '_num_cols = [c for c in _num_df.columns if c not in _skip]\n',
    'outcome = _num_cols[0] if len(_num_cols) > 0 else None\n',
    'treatment = _num_cols[1] if len(_num_cols) > 1 else None\n',
    '_rest = [c for c in _num_cols if c != outcome and c != treatment]\n',
    'mediator = _rest[0] if len(_rest) > 0 else None\n',
    'moderator = _rest[1] if len(_rest) > 1 else None\n',
    'print(f"outcome={outcome}, treatment={treatment}, mediator={mediator}, moderator={moderator}")\n',
  ]));

  // 체크된 항목 수집
  const checkedItems = [];
  for (const g of groups) {
    if (!menu[g]) continue;
    for (const item of menu[g].items) {
      const cb = document.querySelector(`input[data-item-id="${item.id}"]:checked`);
      if (cb) checkedItems.push({ ...item, groupLabel: menu[g].label });
    }
  }

  if (checkedItems.length === 0) {
    cells.push(markdownCell('> ⚠️ No analysis items were selected. Please check items in the ribbon UI and export again.'));
  }

  // 각 분석 항목을 마크다운 + 코드 셀로 추가
  let currentGroup = '';
  checkedItems.forEach((item, idx) => {
    if (item.groupLabel !== currentGroup) {
      currentGroup = item.groupLabel;
      cells.push(markdownCell(`## ${currentGroup}`));
    }

    // 항목 설명 + 참고 링크
    let md = `### ${idx + 1}. ${item.label}\n`;
    if (item.description) {
      md += `\n${item.description}\n`;
    }
    if (item.refLinks && item.refLinks.length > 0) {
      md += '\n**References:**\n';
      item.refLinks.forEach(r => {
        md += `- [${r.label}](${r.url})\n`;
      });
    }
    cells.push(markdownCell(md));

    // 코드에서 편집된 내용이 있으면 반영
    const textarea = document.querySelector(`textarea.code-textarea[data-item-id="${item.id}"]`);
    const code = textarea ? textarea.value : item.code;
    cells.push(codeCell(code));
  });

  // 노트북 JSON 구조
  return {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: 'Python 3',
        language: 'python',
        name: 'python3',
      },
      language_info: {
        name: 'python',
        version: '3.10.0',
      },
    },
    cells,
  };
}

/* ---- 다운로드 ---- */

function downloadNotebook(notebook, filename) {
  const json = JSON.stringify(notebook, null, 1);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || 'analysis_notebook.ipynb';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/* ---- 글로벌 등록 (ui.js에서 호출) ---- */

window.exportAnalysisNotebook = function (menu, mockDataCache) {
  const checkedCount = document.querySelectorAll('input[data-item-id]:checked').length;
  if (checkedCount === 0) {
    alert('내보낼 항목을 하나 이상 선택해주세요.');
    return;
  }
  const notebook = buildNotebook(menu, mockDataCache);
  const timestamp = new Date().toISOString().slice(0, 10);
  downloadNotebook(notebook, `research_analysis_${timestamp}.ipynb`);
};
